scrape_configs:
  - job_name: 'Open VSX Registry input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Open VSX Registry'