logging:
  level:
    org:
      apache:
        http: DEBUG
      eclipse:
        openvsx:
          security: DEBUG
      springframework:
        security: DEBUG

server:
  port: 8080

spring:
  profiles:
    include: ovsx
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: gitpod
    password: gitpod
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.1.0
    baseline-description: JobRunr tables
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never

keycloak:
  realm: OpenVSX
  auth-server-url: http://localhost:9090
  ssl-required: external
  resource: openvsx-server
  bearer-only: true
  credentials:
    secret: QuoCKTvajGjuPhrdMTOUDbTUlZO7xtKV
  use-resource-role-mappings: false
keycloak-service:
    client:
      id: admin-spring-boot
      secret: PsS3wdpGpcx0RKWf8LQE0GeMtku8sIis

management:
  health:
    probes:
      enabled: true

org:
  jobrunr:
    job-scheduler:
      enabled: true
    background-job-server:
      enabled: true
      worker-count: 2
    dashboard:
      enabled: false
    miscellaneous:
      allow-anonymous-data-usage: false

ovsx:
  databasesearch:
    enabled: false
  elasticsearch:
    clear-on-start: true
  eclipse:
    base-url: https://api.eclipse.org
    publisher-agreement:
      timezone: US/Eastern
      version: 1
